default_language_version:
    python: python3.9
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_docs
- repo: git://github.com/bridgecrewio/checkov
  rev: '2.0.330'
  hooks:
    - id: checkov